apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-db
  template:
    metadata:
      labels:
        app: local-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin123"
            - name: POSTGRES_DB
              value: "mydb"
