apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-db
  labels:
    app: local-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-db
  template:
    metadata:
      labels:
        app: local-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: lms-config
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lms-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: lms-config
                  key: POSTGRES_DB

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
